### ISSUE TITLE
Towny's restricted channels are broadcasted globally

### ISSUE THREAD

**Issue by metzg** [MultiChat/Development#95]
**Describe the bug**
Towny implements town and nation channels (/tc and /nc respectively) and messages being sent in these channels should only be visible to residents of a given town/nation.
This feature works properly when players are on the same server, but messages are broadcasted like normal global messages and everyone else on other servers (without Towny even installed) receives them.
This problem also affects other Towny channels (local, mod, admin), but this is less of an issue since mod and admin channels can be replaced with MultiChat's (and I personally don't use Towny's local (distance-based) channel).

The bug is documented in this ticket with two servers behind a Waterfall proxy: `lobby` and `survival`.

**Full startup log of affected servers**
[lobby_latest.log](https://github.com/MultiChat/Development/files/4533706/lobby_latest.log)
[survival_latest.log](https://github.com/MultiChat/Development/files/4533707/survival_latest.log)
[waterfall_latest.log](https://github.com/MultiChat/Development/files/4533708/waterfall_latest.log)

**To Reproduce**
1. Install MultiChat on Waterfall, `lobby`, and `survival`
2. Install Towny, TownyChat, TownyNameUpdater on `survival`
3. Player A joins `survival`
4. Player B joins `lobby`
5. Player A creates a new town and sends a message in town chat (`/tc hello!`)
6. Player B can see that message from `lobby` although Player B is not a resident
7. if Player B joins `survival` and Player A sends another message in `/tc`, Player B will not see it

**Expected behavior**
Messages sent in restricted Towny channels should not be broadcasted to other servers. Maybe with a regex filter on the formatted line being sent across servers? 

An improvement would be the ability to target residents on every server, but this makes the issue much more complex.

**Screenshots**
![Screenshot from 2020-04-25 20-12-49](https://user-images.githubusercontent.com/12766310/80287443-f0b89f80-8731-11ea-9ab0-a26078c3b1b0.png)

**Platform and Versions (please complete the following information):**
 - OS: `Ubuntu 18.04.3 LTS`
 - Java Version: `Java 11` (`openjdk-11-jre-headless`)
 - MultiChat Version: `MultiChat version 1.8.1 by Revilo410`
 - Proxy Version: `Waterfall-327` (`git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327`)
 - Local Server Version: `git-Paper-128`

Thank you for your amazing work on MultiChat!

**Comment by OllieMartin** [comment]
Hi there,

Thank you for creating this detailed report! This is a known issue as such, but you have described it perfectly.

Basically, the problem is that MultiChat handles local and global chat. So if you tell multichat you are in local chat, all messages go locally. And if you tell it you are in global chat, then all messages go glboally.

However, this is an issue, because of the way Towny handles these things. If you type a message in chat, but you have toggled it to towny's town chat mode. Then the chat message is handled as a regular kind of chat message. So multichat sees it, and if you are in global chat mode, then it broadcasts it to all the other servers!

I believe it will be possible to fix this problem. I am not 100% how I will do it yet, but I will work on it in the development builds and hope to come up with a solution soon.

Like you say, to distribute it to town members on other servers would be a next to impossible task as those servers may or may not have towny installed etc. However, to keep the message local should be possible.

MultiChat will likely just have to hook into Towny's API, I just haven't had a proper look at what is possible there yet.

Thanks again for the well-written issue! In the mean time the solution is to use local chat mode when wanting to talk in towny only chat, this should work correcly. Perhaps you could create an alias to switch the user into local chat mode, and then send the towny message?

**Comment by metzg** [comment]
Hi!

Aliasing to `/local /tc` is a clever idea, I will look into it. One drawback is that the user needs the /local permission, and in my case, I would prefer to keep everyone in the global chat at all times (aside from these resident channels).

A specific Towny integration would be great, but if I may suggest a more generic feature as well: the ability to filter fully-formatted messages based on regular expressions. With a configuration format that would for example look like:
```yaml
force_chat: # or a name that makes more sense to you

  # Towny's town/nation channels stay local
  - regex: ^\[\&3TC\]
    chat: local

  - regex: ^\[\&3NC\]
    chat: local

  # Towny's mod channel --> MultiChat's mod chat
  - regex: ^\[\&2MOD\]
    chat: mod

  # Towny's admin channel --> MultiChat's admin chat
  - regex: ^\[\&4ADMIN\]
    chat: admin

  # Some other plugin...
  - regex: "^(.+) thinks: (.+)" 
    chat: current # current is useful because we can stop processing other regexes here

  - regex: "^(.+) slaps (.+) with a trout" 
    chat: local

  - regex: "^(.+) slaps (.+) loudly with a trout" 
    chat: global
```
The formatted messages could then go through each of the regexes in the list and the first one that matches would define the chat to send them to. If match then break early, if nothing matches, default to current chat. An empty list would then just default to current chat, like the current behavior.

That way, filters can be created for all plugins that behave like Towny without requiring specific implementations on your part, and are an easy yet elegant solution for this issue as a whole, until eventually you/someone decides to integrate these plugins with MultiChat.

I unfortunately don't have the time to work on a PR for you at the moment, but I'd be more than happy to test dev builds if you need me to!
